import { FakeData } from "@/types";

export const INITIAL_VISIBLE_COLUMNS = [
  "project",
  "type",
  "who",
  "supp",
  "demand",
  "analist",
  "aprov",
  "dev",
  "test",
  "date",
  "imp",
];

export const columns = [
  { uid: "project", name: "Projeto" },
  { uid: "type", name: "Tipo" },
  { uid: "who", name: "Quem Aplica" },
  { uid: "supp", name: "Fornecedor" },
  { uid: "demand", name: "Demanda" },
  { uid: "analist", name: "Analista Aprovador" },
  { uid: "aprov", name: "Aprovador HML" },
  { uid: "dev", name: "desenvolvedor" },
  { uid: "test", name: "Testes" },
  { uid: "date", name: "Data Implantação" },
  { uid: "imp", name: "Implantação" },
];

export const rows: FakeData[] = [
  {
    key: "1",
    project: "db-manutencao-0.0.18",
    type: "normal - SVN",
    who: "Barnabe Silva",
    supp: "tempN2",
    demand:
      "REQ-22 - Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and.",
    analist: "Marcela Sabino",
    aprov: "Marcela Sabino",
    dev: "Maria Silva",
    test: "Maria Silva",
    date: " - ",
    imp: undefined,
    show: true,
    usersApproved: [],
    usersRefused: [],
    usersIndifferent: [],
  },
  {
    key: "2",
    project: "db-manutencao-0.0.18",
    type: "normal - SVN",
    who: "Barnabe Silva",
    supp: "tempN2",
    demand:
      "REQ-22 - alterando um card onde estava com erro e implementado toda caracterestica do card",
    analist: "Marcela Sabino",
    aprov: "Marcela Sabino",
    dev: "Maria Silva",
    test: "Maria Silva",
    date: " - ",
    imp: undefined,
    show: false,
    usersApproved: [],
    usersRefused: [],
    usersIndifferent: [],
  },
  {
    key: "3",
    project: "db-manutencao-0.0.18",
    type: "normal - SVN",
    who: "Barnabe Silva",
    supp: "tempN2",
    demand:
      "REQ-22 - alterando um card onde estava com erro e implementado toda caracterestica do card",
    analist: "Marcela Sabino",
    aprov: "Marcela Sabino",
    dev: "Maria Silva",
    test: "Maria Silva",
    date: " - ",
    imp: undefined,
    show: false,
    usersApproved: [],
    usersRefused: [],
    usersIndifferent: [],
  },
  {
    key: "4",
    project: "db-manutencao-0.0.18",
    type: "normal - SVN",
    who: "Barnabe Silva",
    supp: "tempN2",
    demand:
      "REQ-22 - alterando um card onde estava com erro e implementado toda caracterestica do card",
    analist: "Marcela Sabino",
    aprov: "Marcela Sabino",
    dev: "Maria Silva",
    test: "Maria Silva",
    date: " - ",
    imp: undefined,
    show: false,
    usersApproved: [],
    usersRefused: [],
    usersIndifferent: [],
  },
  {
    key: "5",
    project: "db-manutencao-0.0.18",
    type: "normal - SVN",
    who: "Barnabe Silva",
    supp: "tempN2",
    demand:
      "REQ-22 - alterando um card onde estava com erro e implementado toda caracterestica do card",
    analist: "Marcela Sabino",
    aprov: "Marcela Sabino",
    dev: "Maria Silva",
    test: "Maria Silva",
    date: " - ",
    imp: undefined,
    show: false,
    usersApproved: [],
    usersRefused: [],
    usersIndifferent: [],
  },
];
